chore: cargo update to fix dep resolution issue
In release build, https://github.com/sstadick/crabz/actions/runs/8317134736/job/22757518845, there is some dependency resolution issue with `env_logger`, thus running `cargo update` to refresh the cargo.lock file

```
 Downloading crates ...
  Downloaded cargo-deb v2.1.0
  Installing cargo-deb v2.1.0
error: failed to compile `cargo-deb v2.1.0`, intermediate artifacts can be found at `/tmp/cargo-installhljkiy`

Caused by:
  failed to select a version for `env_logger`.
      ... required by package `cargo-deb v2.1.0`
  versions that meet the requirements `^0.11` are: 0.11.3, 0.11.2, 0.11.1, 0.11.0

  the package `cargo-deb` depends on `env_logger`, with features: `anstream` but `env_logger` does not have these features.
   It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.

  failed to select a version for `env_logger` which could resolve this conflict
```

Signed-off-by: Rui Chen <rui@chenrui.dev>